'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'

type Setting={key:string,value:string,label:string}
type Chicken={id:string;name:string;breed:string|null;farm_id:string;available_for_sponsorship:boolean;active:boolean;farms?:{name:string}|null}

export default function AdminPage(){
 const[allowed,setAllowed]=useState<boolean|null>(null);const[settings,setSettings]=useState<Setting[]>([]);const[orders,setOrders]=useState<any[]>([]);const[farms,setFarms]=useState<any[]>([]);const[chickens,setChickens]=useState<Chicken[]>([]);const[sponsorships,setSponsorships]=useState<any[]>([]);const[msg,setMsg]=useState('');const[selected,setSelected]=useState<Record<string,string[]>>({});
 const[newFarm,setNewFarm]=useState({name:'',slug:'',postal_code:'',city:''});const[newChicken,setNewChicken]=useState({name:'',breed:'',farm_id:''})
 useEffect(()=>{load()},[])
 async function load(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){setAllowed(false);return}const{data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(profile?.role!=='admin'){setAllowed(false);return}setAllowed(true);const[{data:s},{data:o},{data:f},{data:c},{data:sp}]=await Promise.all([
  supabase.from('site_settings').select('key,value,label').order('sort_order'),
  supabase.from('orders').select('id,user_id,created_at,status,variant,egg_size,chicken_count,monthly_price_cents,contact_data').order('created_at',{ascending:false}).limit(100),
  supabase.from('farms').select('id,name,slug,postal_code,city,active').order('name'),
  supabase.from('chickens').select('id,name,breed,farm_id,available_for_sponsorship,active,farms(name)').order('name'),
  supabase.from('sponsorships').select('id,status,start_date,end_date,eggs_per_week,profiles(first_name,last_name),chickens(name,farms(name))').order('created_at',{ascending:false}).limit(100)
 ]);setSettings((s||[]) as Setting[]);setOrders(o||[]);setFarms(f||[]);setChickens((c||[]) as any);setSponsorships(sp||[])}
 async function save(){const supabase=createClient();for(const x of settings){const{error}=await supabase.from('site_settings').update({value:x.value,updated_at:new Date().toISOString()}).eq('key',x.key);if(error){setMsg(error.message);return}}setMsg('Einstellungen gespeichert.')}
 async function status(id:string,status:string){const supabase=createClient();const{error}=await supabase.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setMsg(error.message);else load()}
 function toggle(orderId:string,chickenId:string,max:number){setSelected(prev=>{const arr=prev[orderId]||[];const next=arr.includes(chickenId)?arr.filter(x=>x!==chickenId):(arr.length<max?[...arr,chickenId]:arr);return{...prev,[orderId]:next}})}
 async function fulfill(o:any){const ids=selected[o.id]||[];if(ids.length!==o.chicken_count){setMsg(`Bitte für diese Bestellung genau ${o.chicken_count} Huhn/Hühner auswählen.`);return}const supabase=createClient();const{error}=await supabase.rpc('fulfill_order',{p_order_id:o.id,p_chicken_ids:ids});if(error){setMsg(error.message);return}setMsg('Bestellung angelegt – Patenschaft und Eierguthaben sind aktiv.');setSelected(x=>({...x,[o.id]:[]}));await load()}
 async function addFarm(){if(!newFarm.name||!newFarm.slug){setMsg('Hofname und Slug fehlen.');return}const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from('farms').insert({...newFarm,owner_id:user.id,description:'',active:true});if(error){setMsg(error.message);return}setNewFarm({name:'',slug:'',postal_code:'',city:''});setMsg('Hof angelegt.');load()}
 async function addChicken(){if(!newChicken.name||!newChicken.farm_id){setMsg('Hühnername und Hof fehlen.');return}const supabase=createClient();const{error}=await supabase.from('chickens').insert({...newChicken,active:true,available_for_sponsorship:true});if(error){setMsg(error.message);return}setNewChicken({name:'',breed:'',farm_id:''});setMsg('Huhn angelegt.');load()}
 async function endSponsorship(id:string){const supabase=createClient();const{error}=await supabase.rpc('end_sponsorship',{p_sponsorship_id:id});if(error)setMsg(error.message);else{setMsg('Patenschaft beendet und Huhn wieder freigegeben.');load()}}
 const available=useMemo(()=>chickens.filter(c=>c.active&&c.available_for_sponsorship),[chickens])
 if(allowed===null)return <main className="main page">Administration wird geladen…</main>
 if(!allowed)return <main className="main page"><div className="card"><h1>Kein Administratorzugang</h1><p className="muted">Dieser Bereich ist nur für Administratorkonten.</p><Link className="btn" href="/login">Anmelden</Link></div></main>
 return <main className="main page"><div className="pageHead"><div className="eyebrow">SCHALTZENTRALE</div><h1 className="pageTitle">Administration</h1><p>Preise, Höfe, Hühner, Bestellungen und laufende Patenschaften zentral verwalten.</p></div>{msg&&<div className="notice">{msg}</div>}
 <div className="adminGrid"><aside className="card adminNav"><a href="#settings">Einstellungen</a><a href="#farms">Höfe & Hühner</a><a href="#orders">Bestellungen</a><a href="#sponsorships">Patenschaften</a><Link href="/hof">Eierausgabe</Link><Link href="/stall">Mein Stall</Link></aside><div>
 <section id="settings" className="card"><h2>Parameter & Inhalte</h2>{settings.map((x,i)=><div className="settingRow" key={x.key}><label>{x.label||x.key}<br/><span className="small muted">{x.key}</span></label><input value={x.value} onChange={e=>setSettings(a=>a.map((v,j)=>j===i?{...v,value:e.target.value}:v))}/></div>)}<button className="btn" onClick={save} style={{marginTop:18}}>Änderungen speichern</button></section>
 <section id="farms" className="card" style={{marginTop:24}}><h2>Höfe & Hühner</h2><div className="miniGrid"><div><h3>Neuen Hof anlegen</h3><div className="field"><label>Name</label><input value={newFarm.name} onChange={e=>setNewFarm(x=>({...x,name:e.target.value}))}/></div><div className="field"><label>Slug</label><input value={newFarm.slug} onChange={e=>setNewFarm(x=>({...x,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')}))}/></div><div className="formGrid"><div className="field"><label>PLZ</label><input value={newFarm.postal_code} onChange={e=>setNewFarm(x=>({...x,postal_code:e.target.value}))}/></div><div className="field"><label>Ort</label><input value={newFarm.city} onChange={e=>setNewFarm(x=>({...x,city:e.target.value}))}/></div></div><button className="btn" type="button" onClick={addFarm}>Hof anlegen</button></div><div><h3>Neues Huhn anlegen</h3><div className="field"><label>Hof</label><select value={newChicken.farm_id} onChange={e=>setNewChicken(x=>({...x,farm_id:e.target.value}))}><option value="">bitte wählen</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div><div className="field"><label>Name</label><input value={newChicken.name} onChange={e=>setNewChicken(x=>({...x,name:e.target.value}))}/></div><div className="field"><label>Rasse</label><input value={newChicken.breed} onChange={e=>setNewChicken(x=>({...x,breed:e.target.value}))}/></div><button className="btn" type="button" onClick={addChicken}>Huhn anlegen</button></div></div><div className="chickenAdminList">{chickens.map(c=><div key={c.id}><strong>🐔 {c.name}</strong><span>{(c.farms as any)?.name||''} · {c.breed||'ohne Rasse'}</span><span className={'statusBadge '+(c.available_for_sponsorship?'open':'redeemed')}>{c.available_for_sponsorship?'verfügbar':'vergeben'}</span></div>)}</div></section>
 <section id="orders" className="card" style={{marginTop:24}}><h2>Bestellungen</h2>{orders.map(o=><article className="orderAdmin" key={o.id}><div className="orderAdminHead"><div><strong>{o.contact_data?.first_name} {o.contact_data?.last_name}</strong><div className="small muted">{new Date(o.created_at).toLocaleString('de-DE')} · {o.variant} · {o.egg_size}</div></div><div><strong>{o.chicken_count} Huhn/Hühner · {(o.monthly_price_cents/100).toFixed(2)} € / Monat</strong><select value={o.status} onChange={e=>status(o.id,e.target.value)}><option value="new">neu</option><option value="confirmed">bestätigt</option><option value="cancelled">storniert</option><option value="fulfilled">angelegt</option></select></div></div>{o.status!=='fulfilled'&&o.status!=='cancelled'&&<div className="assignBox"><strong>Hühner zuordnen ({(selected[o.id]||[]).length}/{o.chicken_count})</strong><div className="checkGrid">{available.map(c=><label key={c.id} className={(selected[o.id]||[]).includes(c.id)?'checked':''}><input type="checkbox" checked={(selected[o.id]||[]).includes(c.id)} onChange={()=>toggle(o.id,c.id,o.chicken_count)}/><span>🐔 {c.name}<small>{(c.farms as any)?.name} · {c.breed||'Rasse offen'}</small></span></label>)}</div><button className="btn" onClick={()=>fulfill(o)}>Patenschaft jetzt anlegen</button></div>}</article>)}</section>
 <section id="sponsorships" className="card" style={{marginTop:24}}><h2>Aktive & beendete Patenschaften</h2><div className="tableWrap"><table className="table"><thead><tr><th>Pate</th><th>Huhn</th><th>Hof</th><th>Start</th><th>Eier/Woche</th><th>Status</th><th></th></tr></thead><tbody>{sponsorships.map(s=><tr key={s.id}><td>{s.profiles?.first_name} {s.profiles?.last_name}</td><td>{s.chickens?.name}</td><td>{s.chickens?.farms?.name}</td><td>{new Date(s.start_date).toLocaleDateString('de-DE')}</td><td>{s.eggs_per_week}</td><td>{s.status}</td><td>{s.status==='active'&&<button className="btn ghost" onClick={()=>endSponsorship(s.id)}>beenden</button>}</td></tr>)}</tbody></table></div></section>
 </div></div></main>
}
