'use client'
import {FormEvent,useState} from 'react'
import {createClient} from '@/lib/supabase/client'

export default function Kontakt(){
 const[form,setForm]=useState({name:'',email:'',subject:'',message:''});const[msg,setMsg]=useState('');const[ok,setOk]=useState(false)
 function set(k:string,v:string){setForm(x=>({...x,[k]:v}))}
 async function submit(e:FormEvent){e.preventDefault();setMsg('');setOk(false);const supabase=createClient();const{error}=await supabase.from('contact_messages').insert(form);if(error){setMsg(error.message);return}const subject=encodeURIComponent(form.subject);const body=encodeURIComponent(`Name: ${form.name}\nE-Mail: ${form.email}\n\n${form.message}`);window.open(`mailto:bobs@posteo.de?subject=${subject}&body=${body}`,'_self');setOk(true);setMsg('Deine Nachricht wurde gespeichert. Dein Mailprogramm wird zum Absenden geöffnet.');}
 return <main className="main page"><div className="pageHead"><div className="eyebrow">KONTAKT</div><h1 className="pageTitle">Schreib uns.</h1><p>Für Fragen zu Patenschaften, Höfen oder bestehenden Eiercodes. Deine Nachricht geht an <a className="inlineLink" href="mailto:bobs@posteo.de">bobs@posteo.de</a>.</p></div><form onSubmit={submit} className="card formCard"><div className="field"><label>Name</label><input value={form.name} onChange={e=>set('name',e.target.value)} required/></div><div className="field"><label>E-Mail</label><input type="email" value={form.email} onChange={e=>set('email',e.target.value)} required/></div><div className="field"><label>Betreff</label><input value={form.subject} onChange={e=>set('subject',e.target.value)} required/></div><div className="field"><label>Nachricht</label><textarea value={form.message} onChange={e=>set('message',e.target.value)} required maxLength={3000}/></div>{msg&&<div className={'notice '+(ok?'success':'error')}>{msg}</div>}<button className="btn">Nachricht absenden</button></form></main>}
